# Use Node.js image
FROM node:20-alpine

# Set the working directory
WORKDIR /app

# Copy package.json and package-lock.json
COPY package.json package-lock.json ./

# Install dependencies
RUN npm install

# Copy the rest of the frontend code
COPY . .

# Expose the Vite development server's default port
EXPOSE 5173

# Start the development server
CMD ["npm", "run", "dev"]


# Serve the app using a lightweight web server
# RUN npm run build #????????
# FROM nginx:alpine
# COPY --from=builder /app/dist /usr/share/nginx/html

# # Expose the port
# EXPOSE 80

# # Start the server
# CMD ["nginx", "-g", "daemon off;"]
