# fly.toml app configuration file generated for goodspeedfrontend on 2025-01-04T17:13:37-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'goodspeedfrontend'
primary_region = 'den'

[build]
  build_target = 'production'
  [build.args]
    API_URL = "https://goodspeedbackend.fly.dev"


[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

  [[services.tls]]
    certs = ["goodspeedparking.info"]

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1