services:
  backend:
    container_name: backend
    build: ./backend
    volumes:
      - ./backend/:/usr/src/app/
      - ./backend/db.sqlite3:/app/db.sqlite3
    ports:
      - "8000:8000"
    environment:
      DJANGO_SETTINGS_MODULE: config.settings
    env_file:
      - ${ENV_FILE:-.env}

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    env_file:
      - ${ENV_FILE:-.env}
    environment:
      - VITE_BACKEND_URL=${BACKEND_URL}
    depends_on:
      - backend