services:

  backend:
    container_name: backend
    build: ./backend
    volumes:
      - ./backend/:/usr/src/app/
      - ./backend/db.sqlite3:/app/db.sqlite3
    ports:
      - "8000:8000"
    environment:
      DJANGO_SETTINGS_MODULE: config.settings
    env_file:
      - ${ENV_FILE:-.env.dev}

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "5173:5173"
    env_file:
      - ${ENV_FILE:-.env.dev}
    environment:
      - VITE_BACKEND_API_URL=${BACKEND_URL}
    depends_on:
      - backend