services:

  backend:
    container_name: backend
    build: ./backend
    volumes:
      - ./backend/:/usr/src/app/
      - ./data/db.sqlite3:/app/db.sqlite3
    ports:
      - "8000:8000"
    environment:
      DJANGO_SETTINGS_MODULE: config.settings