services:

  backend:
    build:
      context: ./backend
      target: ${ENV}
    volumes:
      - ./backend/:/usr/src/app/
      - ./backend/db.sqlite3:/app/db.sqlite3
      - ./backend/media:/usr/src/app/media
    ports:
      - "8000:8000"
    env_file:
      - path: ${ENV_FILE:-.env}

  frontend:
    build:
      context: ./frontend
      target: ${ENV}
      args:
        API_URL: ${BACKEND_URL}
    container_name: frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    env_file:
      - path: ${ENV_FILE:-.env}
    depends_on:
      - backend
