FROM python:3.13-slim as base

# General environment variables
ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1 \
    PATH="/usr/local/bin:$PATH"

# Install required system dependencies
RUN apt-get update && apt-get install -y --no-install-recommends \
    libgl1-mesa-glx \
    libglib2.0-0 \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# Install Python dependencies in a separate layer
COPY requirements.txt /tmp/requirements.txt
RUN pip install --no-cache-dir --upgrade pip && \
    pip install --no-cache-dir -r /tmp/requirements.txt

# App stage to copy code
FROM base AS app

WORKDIR /usr/src/app

# Copy only necessary files to avoid large image size
COPY . /usr/src/app

# Expose port
EXPOSE 8000

#Prod-specific
FROM base AS production

CMD gunicorn --bind :8000 --workers 2 config.wsgi;

#dev-specific
FROM base AS development

RUN pip install debugpy

CMD python manage.py runserver 0.0.0.0:8000;
