# fly.toml app configuration file generated for goodspeedbackend on 2025-01-04T16:23:15-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'goodspeedbackend'
primary_region = 'den'
console_command = '/code/manage.py shell'

[build]

[deploy]
  release_command = 'touch db.sqlite3 && python manage.py migrate'

[env]
  PORT = '8000'
  DEBUG = 'True'
  ENV = 'production'
  BACKEND_URL = 'https://goodspeedbackend.fly.dev'
  FRONTEND_URL = 'https://goodspeedfrontend.fly.dev'
  PROXY_URL = 'https://goodspeedparking.info'
  ALLOWED_HOSTS = 'goodspeedbackend.fly.dev,goodspeedparking.info'
  DATABASE_PATH = '/mnt/db/db.sqlite3'
  MEDIA_PATH = '/mnt/db/media/'


[[mounts]]
  source = 'db'
  destination = '/mnt/db'

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = 'off'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1

[[statics]]
  guest_path = '/code/static'
  url_prefix = '/static/'
