# Generated by Django 5.1.4 on 2024-12-23 00:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=127)),
            ],
        ),
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cam_num', models.IntegerField()),
                ('MAC', models.CharField(max_length=50, unique=True)),
                ('IP', models.GenericIPAddressField()),
                ('garage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cameras', to='app.building')),
            ],
            options={
                'unique_together': {('cam_num', 'garage')},
            },
        ),
        migrations.CreateModel(
            name='ParkingSpot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spot_num', models.IntegerField()),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parking_spots', to='app.camera')),
            ],
            options={
                'unique_together': {('spot_num', 'camera')},
            },
        ),
        migrations.CreateModel(
            name='Vertex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.IntegerField()),
                ('y', models.IntegerField()),
                ('spot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vertex', to='app.parkingspot')),
            ],
        ),
    ]
