# Generated by Django 5.1.4 on 2024-12-23 00:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_vertex_spot'),
    ]

    operations = [
        migrations.RenameField(
            model_name='camera',
            old_name='garage',
            new_name='building',
        ),
        migrations.AlterUniqueTogether(
            name='camera',
            unique_together={('cam_num', 'building')},
        ),
    ]
