# Generated by Django 5.1.4 on 2024-12-30 23:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_garage_camera_building_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='parkingspot',
            unique_together=set(),
        ),
    ]
