# Generated by Django 5.1.4 on 2025-01-02 21:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_uploadedimage'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UploadedImage',
            new_name='Image',
        ),
        migrations.AddField(
            model_name='camera',
            name='image',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='camera', to='app.image'),
        ),
    ]
