# Generated by Django 5.1.5 on 2025-01-20 02:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_remove_parkingspot_monthly_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camera',
            name='image',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='camera', to='app.image'),
        ),
    ]
