# Generated by Django 5.1.6 on 2025-02-08 04:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_zone_parkingspot_zone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parkingspot',
            name='reserved_by_lpn',
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lpn', models.CharField(max_length=12)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('spot', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reservation', to='app.parkingspot')),
            ],
        ),
    ]
