# Generated by Django 5.1.6 on 2025-02-16 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_zone_parkingspot_zone'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkingspot',
            name='location',
            field=models.CharField(max_length=55, null=True),
        ),
    ]
