# Generated by Django 5.1.6 on 2025-02-16 05:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_parkingspot_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parkingspot',
            name='location',
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='app.building')),
            ],
        ),
        migrations.AddField(
            model_name='camera',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cameras', to='app.location'),
        ),
    ]
