# Generated by Django 5.1.6 on 2025-02-17 04:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_image_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReservationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('business_days', models.BooleanField()),
                ('start_time_of_day', models.TimeField()),
                ('end_time_of_day', models.TimeField()),
                ('duration', models.CharField(choices=[('day', 'Day'), ('month', 'Month')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='SpotType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('reservation_basis', models.CharField(choices=[('per_spot', 'Per-spot'), ('per_type', 'Per-type'), ('parkmobile', 'ParkMobile'), ('none', 'None')], max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='parkingspot',
            name='end_datetime',
        ),
        migrations.RemoveField(
            model_name='parkingspot',
            name='reserved_by_lpn',
        ),
        migrations.RemoveField(
            model_name='parkingspot',
            name='start_datetime',
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('LPN', models.CharField(max_length=15)),
                ('spot', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='app.parkingspot')),
                ('reservation_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='app.reservationtype')),
            ],
        ),
        migrations.AddField(
            model_name='reservationtype',
            name='spot_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='app.spottype'),
        ),
        migrations.AddField(
            model_name='parkingspot',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parking_spots', to='app.spottype'),
        ),
    ]
