# Generated by Django 5.1.6 on 2025-02-17 04:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_reservationtype_spottype_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='spottype',
            name='building',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.building'),
            preserve_default=False,
        ),
    ]
