# Generated by Django 5.1.6 on 2025-02-17 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_spottype_building'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservationtype',
            name='end_time_of_day',
        ),
        migrations.RemoveField(
            model_name='reservationtype',
            name='start_time_of_day',
        ),
        migrations.AddField(
            model_name='reservationtype',
            name='active_at',
            field=models.TimeField(default='00:00'),
        ),
        migrations.AddField(
            model_name='reservationtype',
            name='inactive_at',
            field=models.TimeField(default='23:59'),
        ),
    ]
