# Generated by Django 5.1.6 on 2025-02-17 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_remove_reservationtype_end_time_of_day_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservationtype',
            old_name='business_days',
            new_name='only_business_days',
        ),
    ]
