# Generated by Django 5.1.6 on 2025-02-17 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_rename_business_days_reservationtype_only_business_days'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservationtype',
            name='spot_type',
        ),
        migrations.AddField(
            model_name='reservationtype',
            name='spot_type',
            field=models.ManyToManyField(to='app.spottype'),
        ),
    ]
