# Generated by Django 5.1.6 on 2025-02-17 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_remove_reservationtype_spot_type_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservationtype',
            old_name='spot_type',
            new_name='spot_types',
        ),
    ]
